#!/bin/python3

N = int(input())
Q = N % 2
if (Q == 0):
    if(N >= 2):
        if(N <= 5):
            print("Not Weird")
        elif(N >= 6 and N <= 20):
            print("Weird")
        elif(N > 20):
            print("Not Weird")
else:
    print("Weird")
